### ISSUE TITLE
Timestamps not being fixed

### ISSUE THREAD

**Issue by Valinwolf** [kgraefe/pidgin-znc-helper#11]
```
Pidgin 2.13.0 (libpurple 2.13.0)

ZNC Helper
	Author: Konrad Gräfe <konradgraefe@aol.com>
	Version: 1.8
	Website: https://github.com/kgraefe/pidgin-znc-helper
	ID String: gtk-freakazoid-znchelper
	Loadable: Yes
	Loaded: Yes
```

![Screenshot](https://drive.w0lfr.net/index.php/apps/files_sharing/publicpreview/9KL4tNMxGg259AL?x=1366&y=255&a=true&file=Screenshot%2520from%25202019-07-29%252000-23-36.png&scalingup=0)

**Comment by kgraefe** [comment]
What is your ZNC server version?

**Comment by kgraefe** [comment]
Also, did you tick the "Uses ZNC bouncer" checkbox in the accounts settings? You can find that under `Accounts -> $account -> Modify -> Advanced`.

**Comment by Valinwolf** [comment]
@kgraefe that might be the root of the evil... I created the account before I installed the plugin.

As for what version, 1.7.3

**Comment by Valinwolf** [comment]
Yup that works!
