### ISSUE TITLE
Date prefix multiple times

### ISSUE THREAD

**Issue by SammysHP** [kgraefe/pidgin-znc-helper#2]
This seems to be a regression from 1.6 to 1.7. Previously the date was only shown at date changes, now it is shown several times (even without date change). Here is an example:

![20180521_170549](https://user-images.githubusercontent.com/922874/40314676-79877f06-5d19-11e8-9777-34794a16692d.png)

**Comment by kgraefe** [comment]
The old behavior was implemented as quite a hack which caused [bug #1][1]. With the new implementation I decided that formatting the timestamp should not be part if this plugins functionality anymore. I probably could have make that clearer in the change log, though.

By default, Pidgin shows [the date on the first message in a new day, or if the message is older than 20 minutes.][2]

The old behavior could be implemented in another plugin like `Message Timestamp Formats` (shipped with Pidgin), but I don’t think that this has already been done.

[1]: https://github.com/kgraefe/pidgin-znc-helper/issues/1
[2]: https://bitbucket.org/pidgin/main/src/a3b861da06f0c592d37a838696d1fd757c7f0156/pidgin/gtkconv.c?at=release-2.x.y&fileviewer=file-view-default#gtkconv.c-5883

**Comment by SammysHP** [comment]
> or if the message is older than 20 minutes

That's the reason, thank you! With this information I'd call this not a bug but normal behavior in Pidgin.

**Comment by kgraefe** [comment]
I'll add that to the change log though.

**Comment by kgraefe** [comment]
Resolved by bc7347d
